/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Represents a user in the system. */
        User: {
            /** @description The unique identifier for the user. */
            id?: string;
            /** @description The name of the user. */
            name?: string;
            /** @description The email address of the user. */
            email?: string;
        };
        /** @description Represents user preferences. */
        Preference: {
            /** @description The user's preferred currency. */
            currency?: string;
            interactedSplitPeople?: string[];
        };
        /** @description Represents a structured expense record. */
        StructuredExpense: {
            /**
             * Format: date-time
             * @description The timestamp when the expense occurred.
             */
            expenseTimestamp: string;
            /** @description The title of the expense. */
            title: string;
            /** @description The currency of the expense. */
            currency?: string;
            /**
             * Format: float
             * @description The total amount of the expense.
             */
            amount: number;
            /** @description The category of the expense. */
            category: string;
            /** @description A list of tags associated with the expense. */
            tags: string[];
            /** @description A detailed description of the expense. */
            description: string;
            split: components["schemas"]["Split"];
            /** @description The source of payment for the expense (e.g., credit card, cash). */
            paymentSource?: string;
            /** @description Any additional metadata for the expense. */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * @description The status of the expense
             * @enum {string}
             */
            status?: "UNPROCESSED" | "PROCESSED" | "REVIEWED" | "SKIPPED";
            /**
             * @description Training status for the categorization
             * @enum {string}
             */
            trainingStatus?: "PENDING" | "NOT_REQUIRED" | "TRAINED";
        };
        /** @description Represents how the expense is split among participants. The keys are user identifiers and the values are the amounts owed. */
        Split: {
            [key: string]: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
